# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "fire base app distriution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter pub get"
    sh "flutter pub run build_runner build --delete-conflicting-outputs"
    sh "flutter build apk --flavor production --target lib/main.dart"
    firebase_app_distribution(
    app: "1:653026383061:android:7a5aa025637492c3f9be5c",
    firebase_cli_token:ENV['FIREBASE_CLI_TOKEN'],
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    groups: "Testers",
    release_notes: "Auto-distributed via Fastlane"
  )
  end
end
